# Generated by Django 3.2.15 on 2022-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='postreview',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
